name: CI_Build

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest", "macos-latest" ]
#         os: ["windows-latest"]
    steps:
    - uses: actions/checkout@v3
    - name: make bin on ${{ matrix.os }}
      run: | 
        mkdir build 
        cd build
        ls
        cmake .. -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles"
        make bin
        ls
        ./hgs
    - name: test bin on ${{ matrix.os }}
      run: |
        cd build
        ls
        ctest -R bin --verbose
        ls
    - name: make lib on ${{ matrix.os }}
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles"
        make lib
    - name: test lib on ${{ matrix.os }}
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug -G "Unix Makefiles"        
        make lib_test_c
        ctest -R lib --verbose
